### ISSUE TITLE
The service can't render animations

### ISSUE THREAD

**Issue by matvelloso** [Azure/azure-batch-apps-blender#4]
It looks like I'm forced to render only PNGs. So what's the approach if you have an animation with thousands of frames? Render them as PNG, download everything and then stitch together as a single animation?

**Comment by annatisch** [comment]
Hi Mat,

This sample is designed to only deal with images - they need not be PNGs, most of the still image formats are supported. However this sample does not support the video output formats, as the frames are rendered independently of each other.
It's possible to change the task processor in the assemblies to do anything with the frames that you would like, including merge them into a video. Let me know if you're interested and I can provide sample code to do this.

**Comment by matvelloso** [comment]
I think having that as part of the sample would be of huge value. Chances are if you have thousands of frames to render, you're likely up to building a video :) If you have anything even if half done in that space I'd love to take a look at. Thanks!

**Comment by annatisch** [comment]
Thanks Mat - that's really useful feedback.
I will post some sample code here in the meantime, then look at incorporating it properly into the project for the next release.
There are two steps.
The first, is to include FFmpeg.exe into the application image. The executable can be downloaded here:
https://www.ffmpeg.org/download.html
I would recommend downloading the 64-bit static version. This can then be directly extracted into your Blender application image, so that the new directory tree is as follows::

	Blender.zip
	|
	| -- Blender
	|    |
	|    | -- blender.exe
	|    | -- 2.7x directory
	|    | -- other Blender components
	|
	| -- ImageMagick
	|    |
	|    | -- convert.exe
	|    | -- other ImageMagick components
	|
	| -- FFMpeg
	|    |
	|    | -- bin
	|    | -- other FFMpeg directories

The second step is to edit TaskProcessor.cs.
The following two private class properties can be added to the top of the class next to RenderPath and RenderArgs.
```csharp
 /// <summary>
 /// Path to the FFmpeg executable
 /// </summary>
 private string MergePath
 {
     get { return @"FFmpeg\bin\ffmpeg.exe"; }
 }

 /// <summary>
 /// Args with which to run FFmpeg
 /// </summary>
 private string MergeArgs
 {
     //You can add any flags you like here, this is just an example.
     get { return @"-framerate 30 -i {0}_%04d{1} -c:v libx264 -vf fps=30 -crf 0 -y {2}"; }
 }
````

And finally, replace the merge method with the following:
```csharp
/// <summary>
/// Method to execute the external processing for merging the tasks output into job output
/// </summary>
/// <param name="mergeTask">The merge task.</param>
/// <param name="settings">Contains information about the processing request.</param>
/// <returns>The job outputs resulting from the merge process.</returns>
protected override JobResult RunExternalMergeProcess(ITask mergeTask, TaskExecutionSettings settings)
{
    var taskParameters = BlenderParameters.FromTask(mergeTask);
    if (!taskParameters.Valid)
    {
        Log.Error(taskParameters.ErrorText);
        throw new InvalidParameterException(taskParameters.ErrorText);
    }

    var inputFilter = string.Format(CultureInfo.InvariantCulture, "{0}*", taskParameters.Prefix);
    var inputFiles = CollectFiles(LocalStoragePath, inputFilter);
    var inputFormat = Path.GetExtension(inputFiles.First());

    var output = LocalPath(taskParameters.Prefix + ".mp4");

    string externalProcessPath = ExecutablePath(MergePath);
    string externalProcessArgs = string.Format(CultureInfo.InvariantCulture, MergeArgs,
        taskParameters.Start, LocalPath(taskParameters.Prefix), inputFormat, output);

    Log.Info("Calling '{0}' with Args '{1}' for Merge Task / Job '{2}' .", MergePath, externalProcessArgs, mergeTask.JobId);
    var processResult = ExecuteProcess(externalProcessPath, externalProcessArgs);

    if (processResult == null)
    {
        throw new MergeException("Failed to merge outputs.");
    }

    var result = new JobResult { OutputFile = output };
    result.PreviewFile = CreateThumbnail(mergeTask, inputFiles.ToArray());

    return result;
 
}
````

Now rebuild the assemblies and replace them in the Batch Apps portal. This should replace the output.zip that's created on completion with an mp4 video encoded with H.264.
You can check out FFMpegs documentation for their (very extensive) options for video encoding and replace whatever parts you like.

I hope this is helpful - let me know if you have any questions :)

Cheers,
Anna

**Comment by matvelloso** [comment]
This looks great. I'll have a play with that, thanks!
